### ISSUE TITLE
Looking for Python NN repo

### ISSUE THREAD

**Issue by mori-c** [mihok/workshop-apr19#2]
Hey Matthew, great hands-on workshop on the 19th April. Spoke to you after the tutorial and you mentioned how this repo is based on Python code. Couldn't find it; could you share it here?

Thanks.

**Comment by mihok** [comment]
Hey Mori! I've pasted the python tutorial that I build the workshop off of in the Workshop meetup page which you can find here: https://www.meetup.com/torontojs/events/bqlmqpyzfbqb/
